name: Release

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on tags like v1.0.0

jobs:
  build:
    name: Build and Release Binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            ext: ""
          - target: x86_64-pc-windows-gnu
            ext: ".exe"

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust and Add Target
        run: |
          rustup target add ${{ matrix.target }}

      - name: Install cross
        run: cargo install cross

      - name: Build with cross
        run: cross build --release --target ${{ matrix.target }}

      - name: Package binary
        run: |
          mkdir -p dist
          cp target/${{ matrix.target }}/release/nva${{ matrix.ext }} dist/
          cd dist
          zip nva-${{ matrix.target }}.zip nva${{ matrix.ext }}

      - name: Create GitHub Release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          files: dist/nva-*.zip
          draft: true
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
